### ISSUE TITLE
Sky stratification BUG

### ISSUE THREAD

**Issue by LimitXiaoHuoChai** [Jukoz/middle-earth#49]
Game version：1.20.1（Fabric0.14.23）
MOD（Middle-earth-alpha-1.3.0，fabric-api-0.89.3+1.20.1）
After entering the game, the sky of the original world and the world of Middle Earth will appear layered, here are the game screenshots, the author has a look.
When will the next Middle-earth beta be updated? Can I put in the mods I made to share with other players?
The above is from machine translation and may not be accurate.
![2023-10-20_06 05 04](https://github.com/Jukoz/middle-earth/assets/141458306/3f4c5d4f-f8f6-4d44-9e0c-847d334e81bd)
![2023-10-20_06 04 22](https://github.com/Jukoz/middle-earth/assets/141458306/f819c0cc-71a1-443f-9e29-30cab4ce5358)

**Comment by Jukoz** [comment]
Thanks for the report!
It seems the fog is set too far, we'll fix it for the next Alpha release since it's not a game-breaking.

The next update has no date/deadline so we'll release it when we feel like we have enough content & fixed bugs before publishing.

And what do you mean by "Can I put in the mods I made to share with other players?". Put the mods where? (for this question I suggest heading to our discord server so it's easier to communicate).
